### ISSUE TITLE
Missing the Word "Architectures" in the Group Name

### ISSUE THREAD

**Issue by jfc3-dol** [w3c/wai-personalization-standards#10]
While reading through the "Personalization Overview" page ( https://www.w3.org/WAI/personalization/ ), I noticed the "Accessible Platform Working Group (APA WG)" was missing the word "Architectures", which was the what the second "A" in APA stands for.

Please check if it is found in more than one place. I noticed it under the "Who Develops the Personalization Documents" section of the page.

**Comment by shawna-slh** [comment]
https://github.com/w3c/wai-personalization-standards/commit/51993308f00cc8102b3a20cdf9ab61e91f7d098e
