### ISSUE TITLE
[low] update related info; consider renaming repo and netlify site name

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-personalization-standards#11]
Hey, Steve,

we changed URI from:
	https://www.w3.org/WAI/personalization/
to:
	https://www.w3.org/WAI/adapt/

@ruoxiran and I got it updated in the navigation.yml and various pages. I set up a redirect.

I think we need you to update symlinks so the "Fork and Edit" link in the "Help Improve this page" box works.

**Comment by ruoxiran** [comment]
hi @shawna-slh , 
Issue fixed in PR #12 
BTW, I noticed the [preview page in netlify](https://app.netlify.com/sites/wai-personalization-standards/deploys/62bd3c2a5705b8000a559e5b) does not work in this Pull Request, if you want to preview the page, you could use the link at: https://deploy-preview-12--wai-personalization-standards.netlify.app/adapt/

**Comment by SteveALee** [comment]
@shawna-slh @ruoxiran 

That repo and file name are set in the page front matter. The path appears to be missing so it probably never worked. eg

```yaml
github:
  repository: w3c/wai-wcag-supplemental
  path: content/about.md
```

The preview URL is now incorrect as the [netlify.toml redirect](https://github.com/w3c/wai-personalization-standards/blob/master/netlify.toml#L10) needs changing

Generally when changing something as wide reaching as the URL I would do a global search for the old name.

Eventually we should also change the following to avoid confusion:

- repository name and everywhere it is referenced
- Netlify site name

**Comment by shawna-slh** [comment]
Thanks @ruoxiran 

Steve, This is one of the many things that I had on list for you help with, that we didn't get to because of higher priority things. sigh
I decided to try to get it working myself, and revert if not. :-)

I don't expect much traffic in this repo -- mostly just a minor updates from Roy & me a few times a year, so I'm not bothered with getting it all updated right away. (Roy, for now, for previews, just change /perrsonalization/ to /adapt/ :-)

**Comment by SteveALee** [comment]
No problem. There's so many moving parts to get right. I think I'll do a training course -lol

**Comment by remibetin** [comment]
I am closing this PR. The resource has been merged into wai-website, see https://github.com/w3c/wai-website/pull/420
